version: "3.9"
services:
  proxy-server:
    build: proxy-server/
    container_name: "proxy-server"
    network_mode: "host"
    environment:
      - RUST_LOG=debug
  ipfs-server:
    build: ipfs-server/
    container_name: "ipfs-server"
    network_mode: "host"
    environment:
      - RUST_LOG=info
  simpleapikeys-server:
    build: simpleapikeys-server/
    container_name: "simpleapikeys-server"
    network_mode: "host"
    environment:
      - RUST_LOG=info
    depends_on:
      - "db"
  db:
    image: mongo:latest
    container_name: "mongo-db"
    network_mode: "host"
    environment:
      - MONGO_INITDB_DATABASE=lanther
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=supersecretpassword
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/config:/data/configdb
