[package]
name = "ipfs-server"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "^3.3"
clap = "^2.33"
env_logger = "^0.8"
futures = "^0.3"
ipfs-api = { version = "0.11.0", features = ["with-actix"], default-features = false }
log = "^0.4"
serde = "1"
serde_json = "1"

